In [1]:
import random

In [2]:
seed = 500

In [17]:
nd = random.seed(seed)

In [32]:
x = range(0, 101)
y = range(0, 101)


In [40]:
things = ['car', 'house', 'boat']
objects = [[1, 4, 7], [4, 7, 2], [6, 7, 8]]

stuff = {}

def combiner(list1, list2):

    for i in range(len(list1)):

        stuff[list1[i]] = list2[i]

In [41]:
combiner(things, objects)

print(stuff)

{'car': [1, 4, 7], 'house': [4, 7, 2], 'boat': [6, 7, 8]}


In [42]:
stuff['motorcycle'] = [7, 0, 5]

print(stuff)

{'car': [1, 4, 7], 'house': [4, 7, 2], 'boat': [6, 7, 8], 'motorcycle': [7, 0, 5]}


In [54]:
import pandas as pd
import numpy as np

In [44]:
dataframe = pd.DataFrame.from_dict(stuff)

In [45]:
dataframe

car  house  boat  motorcycle
0    1      4     6           7
1    4      7     7           0
2    7      2     8           5

In [46]:
dataframe['multiple_of_house_by_3'] = dataframe['house'] *3




In [47]:
dataframe

car  house  boat  motorcycle  multiple_of_house_by_3
0    1      4     6           7                      12
1    4      7     7           0                      21
2    7      2     8           5                       6

In [50]:
from matplotlib import pyplot as plt

In [56]:
np.matrix([dataframe['car'], dataframe['boat']])

matrix([[1, 4, 7],
        [6, 7, 8]])

In [58]:
mat = np.matrix([[2, 7, -6], [4, 27, -32], [8, 12, -10]])

In [59]:
mat

matrix([[  2,   7,  -6],
        [  4,  27, -32],
        [  8,  12, -10]])

In [60]:
X = [42, 37, 22]

In [65]:
X * (1/mat)

matrix([[ 33.       ,   9.2037037, -10.35625  ]])

plt.plot(dataframe['car'], dataframe['multiple_of_house_by_3'])